[package]
name = "list-as-dependencies"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
publish = false

[dependencies]
cargo-lock = "6.0.1"
itertools = "0.10.0"
semver = "0.11.0"
structopt = "0.3.21"
toml_edit = "0.2.0"
